
package com.odigeo.metasearch.metasearch.ws.v2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.Future;

import javax.xml.namespace.QName;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-08-11T21:09:02.872+02:00
 * Generated source version: 3.1.0
 * 
 */
public final class ItinerarySearchService_ItinerarySearchServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://metasearch.odigeo.com/metasearch/ws/v2/", "ItinerarySearch");

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ItinerarySearch.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ItinerarySearch ss = new ItinerarySearch(wsdlURL, SERVICE_NAME);
        ItinerarySearchService port = ss.getItinerarySearchServicePort();  
        
        {
        System.out.println("Invoking searchAsync...");
        com.odigeo.metasearch.metasearch.ws.v2.PreferencesRequest _searchAsync_preferences = new com.odigeo.metasearch.metasearch.ws.v2.PreferencesRequest();
        _searchAsync_preferences.setLocale("Locale1457293132");
        _searchAsync_preferences.setUserAgent("UserAgent1704845339");
        _searchAsync_preferences.setDomainCode("DomainCode-1679443066");
        _searchAsync_preferences.setRealUserIP("RealUserIP248119621");
        com.odigeo.metasearch.metasearch.ws.v2.SearchRequest _searchAsync_searchRequest = new com.odigeo.metasearch.metasearch.ws.v2.SearchRequest();
        com.odigeo.metasearch.metasearch.ws.v2.ItinerarySearchRequest _searchAsync_searchRequestItinerarySearchRequest = new com.odigeo.metasearch.metasearch.ws.v2.ItinerarySearchRequest();
        java.util.List<com.odigeo.metasearch.metasearch.ws.v2.ItinerarySegmentRequest> _searchAsync_searchRequestItinerarySearchRequestSegmentRequests = new java.util.ArrayList<com.odigeo.metasearch.metasearch.ws.v2.ItinerarySegmentRequest>();
        com.odigeo.metasearch.metasearch.ws.v2.ItinerarySegmentRequest _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1 = new com.odigeo.metasearch.metasearch.ws.v2.ItinerarySegmentRequest();
        com.odigeo.metasearch.metasearch.ws.v2.ItineraryLocationRequest _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure = new com.odigeo.metasearch.metasearch.ws.v2.ItineraryLocationRequest();
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure.setIataCode("IataCode1790772235");
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure.setName("Name-111911812");
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure.setGeoNodeId(Integer.valueOf(-931088361));
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1.setDeparture(_searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure);
        com.odigeo.metasearch.metasearch.ws.v2.ItineraryLocationRequest _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination = new com.odigeo.metasearch.metasearch.ws.v2.ItineraryLocationRequest();
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination.setIataCode("IataCode1543256397");
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination.setName("Name-326216618");
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination.setGeoNodeId(Integer.valueOf(144187509));
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1.setDestination(_searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination);
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-08-11T21:09:02.935+02:00"));
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1.setTime("Time694532327");
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1.setTimeWindow(Integer.valueOf(371963954));
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequests.add(_searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1);
        _searchAsync_searchRequestItinerarySearchRequest.getSegmentRequests().addAll(_searchAsync_searchRequestItinerarySearchRequestSegmentRequests);
        com.odigeo.metasearch.metasearch.ws.v2.CabinClass _searchAsync_searchRequestItinerarySearchRequestCabinClass = com.odigeo.metasearch.metasearch.ws.v2.CabinClass.FIRST;
        _searchAsync_searchRequestItinerarySearchRequest.setCabinClass(_searchAsync_searchRequestItinerarySearchRequestCabinClass);
        _searchAsync_searchRequestItinerarySearchRequest.setNumAdults(1929790044);
        _searchAsync_searchRequestItinerarySearchRequest.setNumChildren(-665968600);
        _searchAsync_searchRequestItinerarySearchRequest.setNumInfants(-912426593);
        _searchAsync_searchRequestItinerarySearchRequest.setResident(Boolean.valueOf(false));
        _searchAsync_searchRequestItinerarySearchRequest.setDirectFlightsOnly(Boolean.valueOf(false));
        _searchAsync_searchRequestItinerarySearchRequest.setMainAirportsOnly(Boolean.valueOf(false));
        _searchAsync_searchRequest.setItinerarySearchRequest(_searchAsync_searchRequestItinerarySearchRequest);
        _searchAsync_searchRequest.setMaxSize(-516134302);
        java.lang.String _searchAsync_metasearchEngineCode = "_searchAsync_metasearchEngineCode1132508779";
        Response<com.odigeo.metasearch.metasearch.ws.v2.SearchResponse> _searchAsync__return = port.searchAsync(_searchAsync_preferences, _searchAsync_searchRequest, _searchAsync_metasearchEngineCode);
        System.out.println("searchAsync.result=" + _searchAsync__return);


        }
        {
        System.out.println("Invoking searchAsync...");
        com.odigeo.metasearch.metasearch.ws.v2.PreferencesRequest _searchAsync_preferences = new com.odigeo.metasearch.metasearch.ws.v2.PreferencesRequest();
        _searchAsync_preferences.setLocale("Locale438482572");
        _searchAsync_preferences.setUserAgent("UserAgent1544249132");
        _searchAsync_preferences.setDomainCode("DomainCode-577629415");
        _searchAsync_preferences.setRealUserIP("RealUserIP-989928518");
        com.odigeo.metasearch.metasearch.ws.v2.SearchRequest _searchAsync_searchRequest = new com.odigeo.metasearch.metasearch.ws.v2.SearchRequest();
        com.odigeo.metasearch.metasearch.ws.v2.ItinerarySearchRequest _searchAsync_searchRequestItinerarySearchRequest = new com.odigeo.metasearch.metasearch.ws.v2.ItinerarySearchRequest();
        java.util.List<com.odigeo.metasearch.metasearch.ws.v2.ItinerarySegmentRequest> _searchAsync_searchRequestItinerarySearchRequestSegmentRequests = new java.util.ArrayList<com.odigeo.metasearch.metasearch.ws.v2.ItinerarySegmentRequest>();
        com.odigeo.metasearch.metasearch.ws.v2.ItinerarySegmentRequest _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1 = new com.odigeo.metasearch.metasearch.ws.v2.ItinerarySegmentRequest();
        com.odigeo.metasearch.metasearch.ws.v2.ItineraryLocationRequest _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure = new com.odigeo.metasearch.metasearch.ws.v2.ItineraryLocationRequest();
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure.setIataCode("IataCode-1965397055");
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure.setName("Name64985863");
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure.setGeoNodeId(Integer.valueOf(1167243821));
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1.setDeparture(_searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure);
        com.odigeo.metasearch.metasearch.ws.v2.ItineraryLocationRequest _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination = new com.odigeo.metasearch.metasearch.ws.v2.ItineraryLocationRequest();
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination.setIataCode("IataCode-1943991773");
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination.setName("Name-1652177500");
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination.setGeoNodeId(Integer.valueOf(1897617483));
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1.setDestination(_searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination);
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-08-11T21:09:02.953+02:00"));
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1.setTime("Time-1498074881");
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1.setTimeWindow(Integer.valueOf(-935560403));
        _searchAsync_searchRequestItinerarySearchRequestSegmentRequests.add(_searchAsync_searchRequestItinerarySearchRequestSegmentRequestsVal1);
        _searchAsync_searchRequestItinerarySearchRequest.getSegmentRequests().addAll(_searchAsync_searchRequestItinerarySearchRequestSegmentRequests);
        com.odigeo.metasearch.metasearch.ws.v2.CabinClass _searchAsync_searchRequestItinerarySearchRequestCabinClass = com.odigeo.metasearch.metasearch.ws.v2.CabinClass.TOURIST;
        _searchAsync_searchRequestItinerarySearchRequest.setCabinClass(_searchAsync_searchRequestItinerarySearchRequestCabinClass);
        _searchAsync_searchRequestItinerarySearchRequest.setNumAdults(793368888);
        _searchAsync_searchRequestItinerarySearchRequest.setNumChildren(-593641375);
        _searchAsync_searchRequestItinerarySearchRequest.setNumInfants(-1621141953);
        _searchAsync_searchRequestItinerarySearchRequest.setResident(Boolean.valueOf(false));
        _searchAsync_searchRequestItinerarySearchRequest.setDirectFlightsOnly(Boolean.valueOf(true));
        _searchAsync_searchRequestItinerarySearchRequest.setMainAirportsOnly(Boolean.valueOf(true));
        _searchAsync_searchRequest.setItinerarySearchRequest(_searchAsync_searchRequestItinerarySearchRequest);
        _searchAsync_searchRequest.setMaxSize(-1607081918);
        java.lang.String _searchAsync_metasearchEngineCode = "_searchAsync_metasearchEngineCode-1023464714";
        AsyncHandler<com.odigeo.metasearch.metasearch.ws.v2.SearchResponse> _searchAsync_asyncHandler = null;
        Future<?> _searchAsync__return = port.searchAsync(_searchAsync_preferences, _searchAsync_searchRequest, _searchAsync_metasearchEngineCode, _searchAsync_asyncHandler);
        System.out.println("searchAsync.result=" + _searchAsync__return);


        }
        {
        System.out.println("Invoking search...");
        com.odigeo.metasearch.metasearch.ws.v2.PreferencesRequest _search_preferences = new com.odigeo.metasearch.metasearch.ws.v2.PreferencesRequest();
        _search_preferences.setLocale("Locale294986387");
        _search_preferences.setUserAgent("UserAgent453633727");
        _search_preferences.setDomainCode("DomainCode-1174720124");
        _search_preferences.setRealUserIP("RealUserIP1090787675");
        com.odigeo.metasearch.metasearch.ws.v2.SearchRequest _search_searchRequest = new com.odigeo.metasearch.metasearch.ws.v2.SearchRequest();
        com.odigeo.metasearch.metasearch.ws.v2.ItinerarySearchRequest _search_searchRequestItinerarySearchRequest = new com.odigeo.metasearch.metasearch.ws.v2.ItinerarySearchRequest();
        java.util.List<com.odigeo.metasearch.metasearch.ws.v2.ItinerarySegmentRequest> _search_searchRequestItinerarySearchRequestSegmentRequests = new java.util.ArrayList<com.odigeo.metasearch.metasearch.ws.v2.ItinerarySegmentRequest>();
        com.odigeo.metasearch.metasearch.ws.v2.ItinerarySegmentRequest _search_searchRequestItinerarySearchRequestSegmentRequestsVal1 = new com.odigeo.metasearch.metasearch.ws.v2.ItinerarySegmentRequest();
        com.odigeo.metasearch.metasearch.ws.v2.ItineraryLocationRequest _search_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure = new com.odigeo.metasearch.metasearch.ws.v2.ItineraryLocationRequest();
        _search_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure.setIataCode("IataCode-475114985");
        _search_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure.setName("Name-1357628899");
        _search_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure.setGeoNodeId(Integer.valueOf(-483631649));
        _search_searchRequestItinerarySearchRequestSegmentRequestsVal1.setDeparture(_search_searchRequestItinerarySearchRequestSegmentRequestsVal1Departure);
        com.odigeo.metasearch.metasearch.ws.v2.ItineraryLocationRequest _search_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination = new com.odigeo.metasearch.metasearch.ws.v2.ItineraryLocationRequest();
        _search_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination.setIataCode("IataCode-1971380529");
        _search_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination.setName("Name-1119736646");
        _search_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination.setGeoNodeId(Integer.valueOf(217485946));
        _search_searchRequestItinerarySearchRequestSegmentRequestsVal1.setDestination(_search_searchRequestItinerarySearchRequestSegmentRequestsVal1Destination);
        _search_searchRequestItinerarySearchRequestSegmentRequestsVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-08-11T21:09:02.958+02:00"));
        _search_searchRequestItinerarySearchRequestSegmentRequestsVal1.setTime("Time1233353497");
        _search_searchRequestItinerarySearchRequestSegmentRequestsVal1.setTimeWindow(Integer.valueOf(935646481));
        _search_searchRequestItinerarySearchRequestSegmentRequests.add(_search_searchRequestItinerarySearchRequestSegmentRequestsVal1);
        _search_searchRequestItinerarySearchRequest.getSegmentRequests().addAll(_search_searchRequestItinerarySearchRequestSegmentRequests);
        com.odigeo.metasearch.metasearch.ws.v2.CabinClass _search_searchRequestItinerarySearchRequestCabinClass = com.odigeo.metasearch.metasearch.ws.v2.CabinClass.FIRST;
        _search_searchRequestItinerarySearchRequest.setCabinClass(_search_searchRequestItinerarySearchRequestCabinClass);
        _search_searchRequestItinerarySearchRequest.setNumAdults(1888282206);
        _search_searchRequestItinerarySearchRequest.setNumChildren(1043474830);
        _search_searchRequestItinerarySearchRequest.setNumInfants(870464417);
        _search_searchRequestItinerarySearchRequest.setResident(Boolean.valueOf(false));
        _search_searchRequestItinerarySearchRequest.setDirectFlightsOnly(Boolean.valueOf(false));
        _search_searchRequestItinerarySearchRequest.setMainAirportsOnly(Boolean.valueOf(false));
        _search_searchRequest.setItinerarySearchRequest(_search_searchRequestItinerarySearchRequest);
        _search_searchRequest.setMaxSize(1150174942);
        java.lang.String _search_metasearchEngineCode = "_search_metasearchEngineCode-1900439515";
        com.odigeo.metasearch.metasearch.ws.v2.SearchStatusResponse _search__return = port.search(_search_preferences, _search_searchRequest, _search_metasearchEngineCode);
        System.out.println("search.result=" + _search__return);


        }

        System.exit(0);
    }

    private ItinerarySearchService_ItinerarySearchServicePort_Client() {
    }

}
