package com.odigeo.metasearch.metasearch.ws.v2;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-08-11T21:09:02.980+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://metasearch.odigeo.com/metasearch/ws/v2/", name = "ItinerarySearchService")
@XmlSeeAlso({ObjectFactory.class})
public interface ItinerarySearchService {

    @WebMethod
    @RequestWrapper(localName = "search", targetNamespace = "http://metasearch.odigeo.com/metasearch/ws/v2/", className = "com.odigeo.metasearch.metasearch.ws.v2.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://metasearch.odigeo.com/metasearch/ws/v2/", className = "com.odigeo.metasearch.metasearch.ws.v2.SearchResponse")
    @WebResult(name = "searchStatus", targetNamespace = "")
    public com.odigeo.metasearch.metasearch.ws.v2.SearchStatusResponse search(
        @WebParam(name = "preferences", targetNamespace = "")
        com.odigeo.metasearch.metasearch.ws.v2.PreferencesRequest preferences,
        @WebParam(name = "searchRequest", targetNamespace = "")
        com.odigeo.metasearch.metasearch.ws.v2.SearchRequest searchRequest,
        @WebParam(name = "metasearchEngineCode", targetNamespace = "")
        java.lang.String metasearchEngineCode
    );

    @WebMethod(operationName = "search")
    @RequestWrapper(localName = "search", targetNamespace = "http://metasearch.odigeo.com/metasearch/ws/v2/", className = "com.odigeo.metasearch.metasearch.ws.v2.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://metasearch.odigeo.com/metasearch/ws/v2/", className = "com.odigeo.metasearch.metasearch.ws.v2.SearchResponse")
    public Response<com.odigeo.metasearch.metasearch.ws.v2.SearchResponse> searchAsync(
        @WebParam(name = "preferences", targetNamespace = "")
        com.odigeo.metasearch.metasearch.ws.v2.PreferencesRequest preferences,
        @WebParam(name = "searchRequest", targetNamespace = "")
        com.odigeo.metasearch.metasearch.ws.v2.SearchRequest searchRequest,
        @WebParam(name = "metasearchEngineCode", targetNamespace = "")
        java.lang.String metasearchEngineCode
    );

    @WebMethod(operationName = "search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://metasearch.odigeo.com/metasearch/ws/v2/", className = "com.odigeo.metasearch.metasearch.ws.v2.SearchResponse")
    @RequestWrapper(localName = "search", targetNamespace = "http://metasearch.odigeo.com/metasearch/ws/v2/", className = "com.odigeo.metasearch.metasearch.ws.v2.Search")
    public Future<?> searchAsync(
        @WebParam(name = "preferences", targetNamespace = "")
        com.odigeo.metasearch.metasearch.ws.v2.PreferencesRequest preferences,
        @WebParam(name = "searchRequest", targetNamespace = "")
        com.odigeo.metasearch.metasearch.ws.v2.SearchRequest searchRequest,
        @WebParam(name = "metasearchEngineCode", targetNamespace = "")
        java.lang.String metasearchEngineCode,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.odigeo.metasearch.metasearch.ws.v2.SearchResponse> asyncHandler
    );
}
