package com.odigeo.metasearch.metasearch.ws.v2;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-08-11T21:09:02.989+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "ItinerarySearch", 
                  wsdlLocation = "http://www.prochainvol.com:8080/bam/Bam?url=http://metasearch.odigeo.com/metasearch/ws/v2/ItinerarySearch?wsdl",
                  targetNamespace = "http://metasearch.odigeo.com/metasearch/ws/v2/") 
public class ItinerarySearch extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://metasearch.odigeo.com/metasearch/ws/v2/", "ItinerarySearch");
    public final static QName ItinerarySearchServicePort = new QName("http://metasearch.odigeo.com/metasearch/ws/v2/", "ItinerarySearchServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://www.prochainvol.com:8080/bam/Bam?url=http://metasearch.odigeo.com/metasearch/ws/v2/ItinerarySearch?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ItinerarySearch.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.prochainvol.com:8080/bam/Bam?url=http://metasearch.odigeo.com/metasearch/ws/v2/ItinerarySearch?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ItinerarySearch() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ItinerarySearch(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ItinerarySearch(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public ItinerarySearch(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    public ItinerarySearch(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ItinerarySearch(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }    




    /**
     *
     * @return
     *     returns ItinerarySearchService
     */
    @WebEndpoint(name = "ItinerarySearchServicePort")
    public ItinerarySearchService getItinerarySearchServicePort() {
        return super.getPort(ItinerarySearchServicePort, ItinerarySearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItinerarySearchService
     */
    @WebEndpoint(name = "ItinerarySearchServicePort")
    public ItinerarySearchService getItinerarySearchServicePort(WebServiceFeature... features) {
        return super.getPort(ItinerarySearchServicePort, ItinerarySearchService.class, features);
    }

}
